version: "3.8"
services:
  frontend:
    build: app
    x-aws-pull_credentials: arn:aws:secretsmanager:ap-northeast-1:123456789012:secret:dockerhubAccessToken-45Y3pu
    image: omuron/timestamper
    ports:
      - "5000:5000"
    depends_on:
      - backend
  backend:
    image: redis:alpine
